apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: characteristic-turtle-java-springboot
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/rhtap-qe:afd7ef4b25ebddbba6b5df1a89a995375741d595@sha256:93f3b4a650f9490dba49cb5df86e601adc9ac551d9de55299f3bfce35eb95ad4
        name: container-image  
