apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: characteristic-turtle-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/characteristic-turtle-java-springboot-gitops